version: '2'
services:
  web:
    build: ./
    volumes:
      - ./app:/app
    ports:
      - "30000:80"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    links:
    - db
db:
  image: mongo:3.0.2
