version: '2'
services:
  web:
    build: ./
    volumes:
      - ./app:/app
    ports:
      - "30000:80"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    links:
      - db
      - elasticSearch
  elasticSearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./app:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  db:
    image: mongo:3.0.2
    ports:
      - "27000:27017"
